[[headers]]
  for = "/*"
  [headers.values]
    "Content-Type" = "text/javascript"
    "X-Content-Type-Options" = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" 